actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than x days (based on index name) for prefixed indices.
      Ignore the error if the filter does not result in an actionable list of
      indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: ${INDEX_PREFIX}
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: ${OLDER_THAN_IN_DAYS}
      exclude:
